### ISSUE TITLE
Weatherstations not available

### ISSUE THREAD

**Issue by laasfuus** [Tumetsu/FMI-weather-downloader#17]
At least Helsinki Kaisaniemi, Helsinki Kumpula, Helsinki Helsinki-Malmi lentoasema. Weatherstations doesn't open.

Error message: "Saatavilla olevia aineistoja ei löytynyt valitulle asemalle."

![image](https://cloud.githubusercontent.com/assets/25526885/22587781/d1579d10-ea0b-11e6-8699-e8818696d5b1.png)

**Comment by Tumetsu** [comment]
After quick investigation it looks like those stations have disappeared from FMI's catalog service meaning that downloader can't find them anymore. At least I could not find them from their [catalog service](http://catalog.fmi.fi/geonetwork/srv/en/main.home).

So in short the problem is with FMI's service :( I'll send them a fault report and we can hope they will fix the problem. Meanwhile you can try to access the daily and real time data with FMIDownloader 0.14.2 since it does not rely on catalog service and thererfore might be able to to download the data you need. Also, it might help if you too can send them a support request listing the stations with missing data here:
https://ilmatieteenlaitos.fi/vikailmoitus-avoimesta-datasta

**Comment by Tumetsu** [comment]
As I expected, the problem was on FMI's catalog service. I got response from them this week and problem has been fixed according to them.
